name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image for Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./client # path to your frontend code
          file: ./client/Dockerfile
          push: true
          tags: boyuan0926/frontend:latest # replace with your Docker Hub username and repository name
          platforms: linux/amd64,linux/arm64 # building the image for both amd64 and arm64 architectures

      - name: Build and Push Docker image for Backend
        uses: docker/build-push-action@v2
        with:
          context: ./server # path to your backend code
          file: ./server/Dockerfile
          push: true
          tags: boyuan0926/backend:latest # replace with your Docker Hub username and repository name
          platforms: linux/amd64,linux/arm64 # building the image for both amd64 and arm64 architectures

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd my_docker_project
          docker-compose down
          docker-compose pull
          docker-compose up -d